defmodule Pokemon.Repo.Migrations.CreatePokemonTable do
  use Ecto.Migration

  # we want to use the pokemon id as the id instead of the
  # autogenerated PK id from ecto
  def change do
    create table(:pokemon, primary_key: false) do
      add :id, :integer, primary_key: true
      add :name, :string
      add :base_experience, :integer
      add :height, :integer
      add :is_default, :boolean
      add :order, :integer
      add :weight, :integer
      add :location_area_encounters, :string
      add :species_id, :integer

      timestamps()
    end
  end
end
